import React from 'react';

const AiAnalysis = () => {
    // Dummy data for the image gallery
    const evidenceImages = [
        { src: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSynnARcJDMRNWx9vaE63OfuaB8mNkb8Q0hbSY4Xm7AqUe1p8Lqdts6N5eHBpI2", alt: "Vessel V-78B", title: "Vessel V-78B Stern View" },
        { src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR5isaeZYNslcc4FgLmiaJ5F2iGIiWP9H6DUPyzF3S5U0r6JVb17ePoZCS0kNUI", alt: "Slick Map", title: "Initial Slick Formation" },
        { src: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSGJ4h5cHHRsc1fq7uEo4qxZgD21BS-j8tTHic6JXEOCJheCoV6-AMMAY0Ua3UR", alt: "Thermal Scan", title: "Thermal Anomaly Scan" },
        { src: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS8tDqqq24X0BdQ-9SO6J8ES0WIDZ1SjvwOiaNM-g8Ear9Aa6qyobtFhMcf_p_c", alt: "Correlation Matrix", title: "Report Correlation Matrix" },
        { src: "https://images.unsplash.com/photo-1603525414899-23a272ff54b1?q=80&w=800", alt: "Witness Photo", title: "Witness Photo 1" }
    ];

    return (
        <div className="widget">
            <div className="widget-header">
                <div className="widget-title"><i className="fas fa-brain widget-icon"></i> AI Report Analysis</div>
            </div>
            <div className="ai-analysis-content">
                <h4 className="summary-title" style={{ fontSize: '0.9rem', marginBottom: '0.75rem' }}>
                    Visual Pattern Analysis: Regional Reports
                </h4>
                <div className="ai-evidence-gallery">
                    {evidenceImages.map((image, index) => (
                        <div className="evidence-image" title={image.title} key={index}>
                            <img src={image.src} alt={image.alt} />
                        </div>
                    ))}
                </div>

                <blockquote>
                    <p>Analysis of correlated reports indicates a <strong>92% probability</strong> that the incident involves a crude oil tanker, designation 'V-78B'.</p>
                    <p>The spill trajectory model predicts landfall near <strong>Alibaug within 18 hours.</strong> Immediate deployment of containment booms is highly recommended.</p>
                </blockquote>
                <div className="ai-footer">
                    Generated by MarineCrisis-AI v2.1
                </div>
            </div>
        </div>
    );
};

export default AiAnalysis;